biblio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from contact.views import MessageAddView

from shelf.views import AuthorListView, AuthorDetailView

# w urlpattern najpierw wyrazenie regularne, potem co ma pokazac
# jezel icos nie jest zaimportowane to podkresla na czerowo
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shelf/', include('shelf.urls', namespace='shelf')),
    url(r'^contact/', MessageAddView.as_view()),
]

# (?P<costam>___)

shelf/urls.py
from django.conf.urls import url

from shelf.views import AuthorListView, AuthorDetailView, BookListView, BookDetailView, PublisherListView, PublisherDetailView

# w urlpattern najpierw wyrazenie regularne, potem co ma pokazac
# jezel icos nie jest zaimportowane to podkresla na czerowo
urlpatterns = [
    url(r'^authors/$', AuthorListView.as_view(), name='author-list'),
    url(r'^authors/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^books/$', BookListView.as_view(), name='book-list'),
    url(r'^books/(?P<pk>\d+)/$', BookDetailView.as_view(), name='book-detail'),
    url(r'^publishers/$', PublisherListView.as_view(), name='publisher-list'),
    url(r'^publishers/(?P<pk>\d+)/$', PublisherDetailView.as_view(), name='publisher-detail'),
]

contact/models.py
#coding: utf-8
from django.db import models

# Create your models here.

class Message(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return "message from {name}".format(name=self.name)

rental/models.py
from django.db import models
from django.contrib.auth.models import User
from shelf.models import BookItem

from django.utils.timezone import now

# Create your models here.

class Rental(models.Model):
    who = models.ForeignKey(User)
    what = models.ForeignKey(BookItem)
    when = models.DateTimeField(default=now())
#    returned = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "{who} {what}, {what}".format(who=self.who,
                                            what=self.what,
                                            when=self.when)

shelf/models.py
from django.db import models

# dodajemy klasy, bo bez klasy nie mozna zdefiniowac obiektu w bazie danych (dla kazdego obiektu klasa)
class Author(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=50)

# str pozwala na wyswietlanie w panelu admina okreslonych danych obiektu zamiast np "Author obcject""
    def __str__(self):
        return "{first_name} {last_name}" .format(first_name = self.first_name, last_name = self.last_name)


class Publisher(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name


class BookCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    cos w rodzaju rekopisu
    """
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(BookCategory)
    # author = models.ForeignKey(Author)

    def __str__(self):
        return self.title

class BookEdition(models.Model):
    """
    wydanie
    """
    book = models.ForeignKey(Book)
    publisher = models.ForeignKey(Publisher)
    date = models.DateField()
    isbn = models.CharField(max_length=17, blank=True)

    def __str__(self):
        return "{book.title}, {publisher.name}".format(book=self.book, publisher=self.publisher)



class BookItem(models.Model):
    """
    egzemnplarz
    """
    edition = models.ForeignKey(BookEdition)
    catalogue_numb = models.CharField(max_length=30)
#    cover_type = models.CharField(max_length=4, choices=COVER_TYPES)
    hard = 'Hard'
    soft = 'Soft'
    COVER_TYPES = (
        ('soft', 'Soft'),
        ('hard', 'Hard'),
        # wartosc w bazie, wartosc wysywietlana
    )

    cover_type = models.CharField(
        max_length=4,
        choices=COVER_TYPES,
        default=soft,
    )

    def __str__(self):
        return "{edition}, {cover}, {number}".format(edition=self.edition,
                                                     #cover=self._get_FIELD_display(self.cover_type),
                                                     cover=self.cover_type in (self.soft, self.hard),
                                                     number=self.catalogue_numb)


#16:40
#odc 5 (55:00) - omawia korzystanie z shella - WAZNE

contact/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'message')

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

contact/views.py
from django.views.generic import ListView, DetailView, FormView # klasy do pokazywania list i szczegolow modelu
# importuje model Author
from .models import Message
from .forms import MessageForm, ContactForm

class MessageDetailView(DetailView):
    model = Message

class MessageAddView(FormView):
    form_class = ContactForm
    template_name = 'contact/message_form.html'
    success_url = '/'

#    def form_invalid(self, form):
#        form.save() #bo form jest instancja ModelForm ktory posiada metode seve()
#        return super(MessageAddView, self).form_valid(form)

rental/views.py
from django.shortcuts import render

# Create your views here.

shelf/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView # klasy do pokazywania list i szczegolow modelu
# importuje model Author
from .models import Author, Book, Publisher


class AuthorListView(ListView):
    model = Author

class AuthorDetailView(DetailView):
    model = Author

class BookListView(ListView):
    model = Book

class BookDetailView(DetailView):
    model = Book

class PublisherListView(ListView):
    model = Publisher

class PublisherDetailView(DetailView):
    model = Publisher

contact/templates/contact/message_form.html
{% extends "base.html" %}

{% block 'content' %}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <button type="submit">Wyślij</button>
</form>
{% endblock %}

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block 'content' %}
Detale autorów:
<a href="{% url 'shelf:author-list' %}">Powrót do listy autorów</a>

Autor: {{ object.last_name }} {{ object.first_name }}


{% endblock %}

shelf/templates/shelf/author_list.html
{% extends "base.html" %}

{% block 'content' %}
Lista autorów:

<ul>
{% for author in object_list %}
	<li> <a href="{% url 'shelf:author-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a></li>
	{{ author.id }}
	{% endfor %}

</ul>



{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %}

{% block 'content' %}
Detale ksiazek:
<a href="{% url 'shelf: book-detail' %}">Powrót do listy ksiazek</a>

Book: {{ object.title }} {{ object.author }}


{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}

{% block 'content' %}
Lista ksiazek:

<ul>
{% for book in object_list %}
	<li> <a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }} {{ book.author }}</a></li>
	{% endfor %}

</ul>

{% endblock %}

shelf/templates/shelf/publisher_detail.html
{% extends "base.html" %}

{% block 'content' %}
Detale wydawców:
<a href="{% url 'shelf:publisher-list' %}">Powrót do listy autorów</a>

Autor: {{ object.name }}


{% endblock %}

shelf/templates/shelf/publisher_list.html
{% extends "base.html" %}

{% block 'content' %}
Lista wydawców:

<ul>
{% for publisher in object_list %}
	<li> <a href="{% url 'shelf:publisher-detail' publisher.id %}">{{ publisher.name }}</a></li>
	{% endfor %}

</ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <!-- tresc strony -->
    {% block 'content' %}
    {% endblock %}
</body>
</html>